name: compliance-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7

  # dash packages
  - dash

  # general packages
  - numpy
  - pandas
  - pyarrow
  - lxml
  - flask
  - python-dateutil

  # needed for dash-auth
  - requests

  # development
  - black
  - pytest

#  # pip packages
#  - pip
#  - pip:
#    - flask-caching
