name: compliance-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7

  # dash packages
  - dash
  - flask

  # general packages
  - lxml
  - numpy
  - pandas
  - pyarrow
  - python-dateutil

  # development
  - black
  - pytest
  - toml
  - isort

#  # pip packages
#  - pip
#  - pip:
#    - flask-caching
