name: compliance-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7

  # dash packages
  - dash
  - flask

  # general packages
  - lxml
  - numpy
  - pandas
  - pyarrow
  - python-dateutil
  - redis

  # development
  - black
  - pytest
  - toml
  - isort
#
#  # ci
#  - gunicorn

  # pip packages
  - pip
  - pip:
    - flask-caching
